# Sets up two Kafka Clusters, each with one broker and a Connect cluster with one node.
# No SSL/SASL is used, auto create topics is enabled and everyone hos access to resources if no ACLS are used
# Local broker  : Internal port  : 19092
#                 Forwarded port : 9092
# Remote broker : Internal port  : 19093
#                 Forwarded port : 9093
# Connect node  : Internal port  : 8082
#                 Forwarded port : 8082
---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  brokerLocal:
    image: confluentinc/cp-kafka:6.2.1
    hostname: local-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/localCluster'
      KAFKA_ADVERTISED_LISTENERS: 'INNER://local-broker:19092,OUTER://localhost:9092'
      KAFKA_LISTENERS: 'INNER://local-broker:19092,OUTER://local-broker:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INNER:PLAINTEXT,OUTER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INNER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'

  brokerRemote:
    image: confluentinc/cp-kafka:6.2.1
    hostname: remote-broker
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/remoteCluster'
      KAFKA_ADVERTISED_LISTENERS: 'INNER://remote-broker:19093,OUTER://localhost:9093'
      KAFKA_LISTENERS: 'INNER://remote-broker:19093,OUTER://remote-broker:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INNER:PLAINTEXT,OUTER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INNER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'

  connect:
    image: confluentinc/cp-kafka-connect:6.2.1
    hostname: connect
    depends_on:
      - brokerLocal
    volumes:
      - ./plugins:/plugins
    ports:
      - "8082:8082"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'local-broker:19092'
      CONNECT_REST_PORT: '8082'
      CONNECT_GROUP_ID: 'connect-quickstart'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-quickstart-config'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-quickstart-offsets'
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-quickstart-status'
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'localhost'
      CONNECT_PLUGIN_PATH: '/plugins'

