version: '3.1'

services:
  zookeeper:
    image: zookeeper:3.6.2
    hostname: zookeeper
    container_name: bitzookeeper
    restart: always
    environment:
      ZOO_TICK_TIME: "2000"
      ZOO_STANDALONE_ENABLED: "true"

  broker:
    image: bitnami/kafka:3.6.1
    hostname: kafka-broker-1
    container_name: bitbroker
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./broker/config:/config
    entrypoint: [ "kafka-server-start.sh", "/config/broker-1.properties" ]
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"

  connect:
    image: bitnami/kafka:3.6.1
#    build: connect-build
    hostname: kafka-connect-1
    container_name: bitconnect
    restart: always
    depends_on:
      - broker
    ports:
      - "9001:9001"
      - "5005:5005"
      - "9999:9999"
    volumes:
      - ./plugin-jars:/plugins
      - ./connect/config:/config
      - ./connect/data:/data
    entrypoint: [ "connect-distributed.sh", "/config/worker.properties" ]
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
      KAFKA_OPTS: "-Dlog4j.configuration=file:/data/log4j.properties -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      EXTRA_ARGS: "-Dorg.apache.cxf.logger=org.apache.cxf.common.logging.Slf4jLogger"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9999 -Djava.rmi.server.hostname=127.0.0.1"
      JMX_PORT: "9999"

  schemaregistry:
    image: bitnami/schema-registry:7.5
    container_name: bitregistry
    ports:
      - '8081:8081'
    depends_on:
      - broker
    environment:
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka-broker-1:9091

  kafka-ui:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./kafka-ui:/config
    environment:
      CONFIG_FILEPATH: "/config/kafka-ui-config.yaml"

