server:
  listenPort: 8080
  listenAddress: 0.0.0.0

kafka:
  brokers:
    - kafka-broker-1:9091
  schemaRegistry:
    enabled: true
    urls: ["http://schemaregistry:8081"]

connect:
  enabled: true
  clusters:
    - name: Connect-1
      url: http://kafka-connect-1:9001
